name: cleangene
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10
  - shovill
  - prokka
  - panaroo
  - bwa
  - samtools=1.20
  - bcftools
  - minimap2
  - fastp
  - kraken2
  - pip: 
    - .
